version: '3.8'
services:
  zram-gui:
    build: .
    environment:
      - DISPLAY=:99
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/systemd/zram-generator.conf:/etc/systemd/zram-generator.conf
    privileged: true  # for systemd/zram
    stdin_open: true
    tty: true

